// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunk.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countChunksByFileID = `-- name: CountChunksByFileID :one
SELECT COUNT(*)::int AS total
FROM file_chunks
WHERE file_id = $1
`

func (q *Queries) CountChunksByFileID(ctx context.Context, fileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countChunksByFileID, fileID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countUploadedChunksByFileID = `-- name: CountUploadedChunksByFileID :one
SELECT COUNT(*)::int AS total
FROM file_chunks
WHERE file_id = $1 AND uploaded = TRUE
`

func (q *Queries) CountUploadedChunksByFileID(ctx context.Context, fileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUploadedChunksByFileID, fileID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO file_chunks (id, file_id, chunk_index, uploaded, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateChunkParams struct {
	ID         uuid.UUID        `json:"id"`
	FileID     uuid.UUID        `json:"file_id"`
	ChunkIndex int32            `json:"chunk_index"`
	Uploaded   pgtype.Bool      `json:"uploaded"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.Exec(ctx, createChunk,
		arg.ID,
		arg.FileID,
		arg.ChunkIndex,
		arg.Uploaded,
		arg.CreatedAt,
	)
	return err
}

const getUploadedChunkIndices = `-- name: GetUploadedChunkIndices :many
SELECT chunk_index
FROM file_chunks
WHERE file_id = $1 AND uploaded = TRUE
ORDER BY chunk_index
`

func (q *Queries) GetUploadedChunkIndices(ctx context.Context, fileID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUploadedChunkIndices, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var chunk_index int32
		if err := rows.Scan(&chunk_index); err != nil {
			return nil, err
		}
		items = append(items, chunk_index)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChunkUploaded = `-- name: MarkChunkUploaded :exec
UPDATE file_chunks SET uploaded = TRUE, etag = $3
WHERE file_id = $1 AND chunk_index = $2
`

type MarkChunkUploadedParams struct {
	FileID     uuid.UUID   `json:"file_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Etag       pgtype.Text `json:"etag"`
}

func (q *Queries) MarkChunkUploaded(ctx context.Context, arg MarkChunkUploadedParams) error {
	_, err := q.db.Exec(ctx, markChunkUploaded, arg.FileID, arg.ChunkIndex, arg.Etag)
	return err
}
