// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, owner_id, filename, object_key, size, content_type, status, checksum, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateFileParams struct {
	ID          uuid.UUID        `json:"id"`
	OwnerID     uuid.UUID        `json:"owner_id"`
	Filename    string           `json:"filename"`
	ObjectKey   string           `json:"object_key"`
	Size        int64            `json:"size"`
	ContentType pgtype.Text      `json:"content_type"`
	Status      string           `json:"status"`
	Checksum    pgtype.Text      `json:"checksum"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.OwnerID,
		arg.Filename,
		arg.ObjectKey,
		arg.Size,
		arg.ContentType,
		arg.Status,
		arg.Checksum,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, owner_id, filename, object_key, size, content_type, status, checksum, created_at, updated_at, scan_result, scanned_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ObjectKey,
		&i.Size,
		&i.ContentType,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanResult,
		&i.ScannedAt,
	)
	return i, err
}

const getFileByIDAndOwner = `-- name: GetFileByIDAndOwner :one
SELECT id, owner_id, filename, object_key, size, content_type, status, checksum, created_at, updated_at, scan_result, scanned_at
FROM files
WHERE id = $1 AND owner_id = $2 AND status != 'DELETED'
`

type GetFileByIDAndOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetFileByIDAndOwner(ctx context.Context, arg GetFileByIDAndOwnerParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByIDAndOwner, arg.ID, arg.OwnerID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ObjectKey,
		&i.Size,
		&i.ContentType,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanResult,
		&i.ScannedAt,
	)
	return i, err
}

const listFilesByOwner = `-- name: ListFilesByOwner :many
SELECT id, owner_id, filename, object_key, size, content_type, status, checksum, created_at, updated_at, scan_result, scanned_at
FROM files
WHERE owner_id = $1 AND status != 'DELETED'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFilesByOwnerParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListFilesByOwner(ctx context.Context, arg ListFilesByOwnerParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.ObjectKey,
			&i.Size,
			&i.ContentType,
			&i.Status,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScanResult,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET status = 'DELETED', updated_at = NOW()
WHERE id = $1 AND owner_id = $2
`

type SoftDeleteFileParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) error {
	_, err := q.db.Exec(ctx, softDeleteFile, arg.ID, arg.OwnerID)
	return err
}

const updateFileScanResult = `-- name: UpdateFileScanResult :exec
UPDATE files
SET status = $2, scan_result = $3, scanned_at = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateFileScanResultParams struct {
	ID         uuid.UUID        `json:"id"`
	Status     string           `json:"status"`
	ScanResult pgtype.Text      `json:"scan_result"`
	ScannedAt  pgtype.Timestamp `json:"scanned_at"`
}

func (q *Queries) UpdateFileScanResult(ctx context.Context, arg UpdateFileScanResultParams) error {
	_, err := q.db.Exec(ctx, updateFileScanResult,
		arg.ID,
		arg.Status,
		arg.ScanResult,
		arg.ScannedAt,
	)
	return err
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE files SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFileStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.Exec(ctx, updateFileStatus, arg.ID, arg.Status)
	return err
}
