// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID          uuid.UUID        `json:"id"`
	OwnerID     uuid.UUID        `json:"owner_id"`
	Filename    string           `json:"filename"`
	ObjectKey   string           `json:"object_key"`
	Size        int64            `json:"size"`
	ContentType pgtype.Text      `json:"content_type"`
	Status      string           `json:"status"`
	Checksum    pgtype.Text      `json:"checksum"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ScanResult  pgtype.Text      `json:"scan_result"`
	ScannedAt   pgtype.Timestamp `json:"scanned_at"`
}

type FileChunk struct {
	ID         uuid.UUID        `json:"id"`
	FileID     uuid.UUID        `json:"file_id"`
	ChunkIndex int32            `json:"chunk_index"`
	Etag       pgtype.Text      `json:"etag"`
	Uploaded   pgtype.Bool      `json:"uploaded"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	FullName     pgtype.Text      `json:"full_name"`
	AvatarUrl    pgtype.Text      `json:"avatar_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
